### ISSUE TITLE
Inputs: set the value via JS (e.g. angular patchValue()) should trigger instance.forceActive()

### ISSUE THREAD

**Issue by osahner** [mdbootstrap/TW-Elements#1743]
Trying to update the value of an Input element in angular via . patchValue() doesn't update the input element active status (put notch up etc.)

I tried a workaround with something like this
file: src/js/input.js 
```ts
    // line 374
    EventHandler.on(this.input, "change", (e) => {
      const instance = Input.getInstance(e.target.parentNode);
      if (!instance) {
        return;
      }
      if (e.target.value?.length > 0) {
        instance.forceActive();
      }
    });
```

don't know if there are any negative consequences ...

**Comment by juujisai** [comment]
Hi, you can trigger the focus inside the `patchValues` method:

```
  patchValues() {
    const formValues = {
      firstName: 'John Doe',
    };
    this.myForm.patchValue(formValues);
    (
      document.querySelector(
        '[data-te-input-wrapper-init] input'
      ) as HTMLElement
    ).focus();
  }
```

**Comment by osahner** [comment]
Doesn't work unfortunately.

**Comment by smessmer** [comment]
Running into the same issue with the [leptos](https://leptos.dev/) framework which reactively binds to the "value" property of the input element, i.e. sets the value via the JavaScript property.

It's not just that `data-te-input-state-active` is missing (and therefore the label is just always on top of the field), but it also doesn't generate the border around the input field.

Note that I'm loading the UWP library of twelements, but due to the web framework I'm using, those input elements may have been created before or after that javascript executed.

**Comment by juujisai** [comment]
@smessmer Did you try initializing via JS?

```
const myInput = new Input(
  document.getElementById("myInput")
);

```

**Comment by smessmer** [comment]
hm doing that from the browser console causes:

```
const myInput = new te.Input(document.getElementById("my-input-id"))
twelements.js:18 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at Z._showPlaceholder (twelements.js:18:9117)
    at Z._getLabelData (twelements.js:18:6700)
    at Z.init (twelements.js:18:5859)
    at new Z (twelements.js:18:5704)
    at <anonymous>:1:17
```

For line number reference, I'm using `node_modules/tw-elements/dist/js/tw-elements.umd.min.js` of `tw-elements 1.0.0-rc.1`.

**Comment by juujisai** [comment]
@smessmer Try passing an input wrapper instead of the input

For example
```
<div id="inputWrapper">
  <input/><label>Example label</label>
</div>

new Input(document.querySelector("#inputWrapper"));
```

**Comment by smessmer** [comment]
yes, calling `new Input()` on it works. Thanks.

I'm now emitting `<script>` tags with that code next to my each of my input fields. Is this the right way of doing it? Seems weird and this might cause elements to be initialized multiple times. Can't tailwind elements automatically recognize and install elements that are added to the DOM? The framework I'm using could manipulate the DOM and add or remove DOM elements at any time though.

**Comment by juujisai** [comment]
@smessmer Generally a single script tag add the bottom of the body element (or depending on the framework) is enough and should contain all of the inits necessary for your app. In most frameworks, it works the best if put inside the function that runs after component is beeing mounted.

Your elements shouldn't be initialized mulitple times. If you are affraid that it may happen though, you can add some kind of flag before initializing the components, for example 

```
if (!wasInitialized) {
 new Input(...)
wasInitialized = true
}
```

We decided, that we will only leave the automatic initialization in the UMD format of TE package. Moving the initialization to the `initTE` method, or via the JS in ES format allows to decide what and should be initialized. It also allows for treeshaking.

**Comment by smessmer** [comment]
I do use the UMD version and I was expecting it to auto-initialize all fields that I annotate with the corresponding `init` attributes, but that doesn't seem to happen, that's why I reached out. Adding the per-element script tag to initialize that specific element does make it work but is cumbersome.

My best guess for why it doesn't work is that the framework might create those elements and add them to the dom after the UMD already parsed and initialized the site. I'm using the Leptos framework (rust wasm, reactive) but not sure if that matters, I think any framework, even react, can create new components based on state changes after the website is already loaded and the UMD initialization already ran.

**Comment by juujisai** [comment]
Maybe try importing the package after you app mounts (for example with use of asyncs `await import('tw-elements')`. 

Frameworks like react will work better with ES format. The components are beeing initialized after the component mounts (with initTE method or via JS) and reinitialized when they mount again (thats why we added the `allowReinits` option to the initTE method)

**Comment by smessmer** [comment]
That won't help because the DOM is manipulated after the app is already mounted. And I don't think ES would make a difference unless the framework somehow re-calls `initTE` whenever there is a DOM change, which might be difficult to do depending on the framework (not sure if even react supports it).

Btw it looks like this is a separate issue from what was actually being discussed here, sorry for hijacking it. I created a new issue: https://github.com/mdbootstrap/Tailwind-Elements/issues/1935
