### ISSUE TITLE
[Select] [Content not readable in dark mode]

### ISSUE THREAD

**Issue by MGeurts** [mdbootstrap/TW-Elements#2023]
**Describe the bug**
In dark mode, the TWE **Select** component uses `dark:text-gray-200` by default. This value is hard to read.

**Additional context**
The default `dark:text-gray-200` can not be overruled by wrapping the component in `div class="!dark:text-neutral-800"></div>`.

Please adjust the default value or let us overrule the default.

**Comment by juujisai** [comment]
You can customize classes via data attributes. For example I changed the border colors to `dark:border-yellow-600` from `dark:border-neutral-600`:

```
    <select 
      data-te-select-init id="select-1"
      data-te-class-notch-leading-normal="border-neutral-300 dark:border-yellow-600 group-data-[te-input-focused]:shadow-[-1px_0_0_#3b71ca,_0_1px_0_0_#3b71ca,_0_-1px_0_0_#3b71ca] group-data-[te-input-focused]:border-primary"
      data-te-class-notch-middle-normal="border-neutral-300 dark:border-yellow-600 group-data-[te-input-focused]:shadow-[0_1px_0_0_#3b71ca] group-data-[te-input-focused]:border-primary"
      data-te-class-notch-trailing-normal="border-neutral-300 dark:border-yellow-600 group-data-[te-input-focused]:shadow-[1px_0_0_#3b71ca,_0_-1px_0_0_#3b71ca,_0_1px_0_0_#3b71ca] group-data-[te-input-focused]:border-primary"
      >
      <option value="1">One</option>
      <option value="2">Two</option>
      <option value="3">Three</option>
      <option value="4">Four</option>
      <option value="5">Five</option>
    </select>
```
    
Visit the API tabs of select and input (section classes) to see what you can customize and what styles apply:
https://tw-elements.com/docs/standard/forms/select/#docsTabsAPI
https://tw-elements.com/docs/standard/forms/inputs/#docsTabsAPI


---
`div class="!dark:text-neutral-800"></div>` won't work, because you have to add the `!` after the `dark`: like this `div class="dark:!text-neutral-800"></div>`

**Comment by MGeurts** [comment]
OK. I didn't know about the API part. Me stupid. Thanks.
