### ISSUE TITLE
License AGPL

### ISSUE THREAD

**Issue by lesar** [mdbootstrap/TW-Elements#2315]
Forgive my bad english.  

I ask if I can use TWE AGPL to sell a web site.  

Example: a men that sell sausages, would like that I build a web site for him to promote end sell his sausages.  

Can I build a site using TWE AGPL and sell the site getting back money for my work OR must I put AGPL on that site too and give it to the  sausages sellers man for nothing (gratis, no money)?

I thing that is no a bad idea if you put some basic examples on your license page.  

On Internet this AGPL is not easy to understand

from [ospo.co](https://ospo.co/blog/questions-and-answers-about-the-agpl/)
> The microservices trap
> 
> What many people miss is the possible creation of derivative works when AGPL-licensed code is used in a networked, distributed application.
> 
> Normally, a "program" is a discrete thing. It has known limits. The copyright (and the open source license) usually stops at a process or network boundary.
> 
> But that is not necessarily true when the "application" is a distributed application. The common "microservices" architecture creates a single web application by coordinating the use of multiple services running on multiple servers. Each service handles one distinct aspect of the larger application (like authentication, or database access).
> 
> In this case, each individual service is its own, copyrightable work. But each service is also a sub-component of the larger application.
> 
> In this way, creating a multi-component distributed application is like taking a short story and including it with other stories to create a "Best stories of the year" compilation. Even if the AGPL-licensed software itself is not modified, the distributed application that includes the AGPL-licensed software has "adapted all" of the code, probably "in a fashion requiring copyright permission."
> 
> There are some applications that try to avoid this expansive reading of the AGPL by specifically disclaiming anything but the server itself - but this requires scouring each project's website and evaluating the strength of the disclaimer. 

can you help me?

best regards,
Leonardo

**Comment by filipkappa** [comment]
Hello,

You can charge the sausage man for your service of building the website, but the website you built has to be released in open source, with an AGPL license (i.e. on GitHub).

AGPL is focused on sharing knowledge and driving innovation - this forces you to publish any new layouts/components you add, and enrich the community of the project.

Of course, we understand that the AGPL may not be the best fit for some specific use cases, which is why we have implemented a dual licensing model. This allows us to offer TW Elements under the AGPL for those who share our commitment to open-source values, while also offering a custom license for those who need a more permissive license for their specific use case.

If you need a non-AGPL license you can check it out here:
https://tw-elements.com/pro/

Keep coding!
